WIP: Move CustomConfig* tests to the separate Maven test execution
jboss-eap-qe/eap-microprofile-test-suite pull request #221
Opened 2020-09-07 13:29 UTC by zhantemirov

Hi @istraka 

After some MP Config studying and Metrics failures [1] investigation I tried to fix those failures, though I'm not quite sure whether this is the correct way.

So the main issue was the unset `config.source.properties.path` system property. I added the existing SetupTask class to the ServerSetup annotation to all failing test cases.

I'd like to hear your opinions regarding the solution (and maybe another ones) from you, guys - @istraka @fabiobrz, thanks!

[1] -https://eap-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/eap-7.x-microprofile-testsuite/jdk=oracle-java-11,label_exp=RHEL7/353/#showFailuresLink

Passing job - https://eap-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/eap-7.x-microprofile-testsuite/jdk=oracle-java-11,label_exp=RHEL7/355/

Please make sure your PR meets the following requirements:
- [X] Pull Request contains a description of the changes
- [X] Pull Request does not include fixes for multiple issues/topics
- [X] Code is formatted, imports ordered, code compiles and tests are passing
- [X] Link to the passing job is provided
- [X] Code is self-descriptive and/or documented
- [X] Description of the tests scenarios is included (see #46)

2020-09-07 14:01 UTC, istraka commented
`config.source.properties.path` property is supposed to be used by `CustomConfigSource` which is added as module. Its purpose is to load MP Config properties from file dynamically and provide them for MP Config itself. The property should not be needed anywhere else. IMO using `CustomConfigSource` setup class for tests that aren't designed to use it is a not a good idea.

```
So the main issue was the unset config.source.properties.path system property
```
I see the change in `CustomMetricCustomConfigSourceTest.SetupTask#tearDown()` where removing the property was missing. Yes, the setupTask should remove the property. But the presence should matter only in `CustomMetricCustomConfigSourceTest` and `CustomMetricCustomConfigSourceProviderTest`

The exception comes from https://github.com/jboss-eap-qe/eap-microprofile-test-suite/blob/master/microprofile-health/src/main/java/org/jboss/eap/qe/microprofile/health/integration/CustomConfigSource.java#L23

This class should be used only with that two test classes as a module. Can you look into why the module is presented?

2020-09-07 14:02 UTC, istraka requested changes
See the comment.

2020-09-09 10:42 UTC, zhantemirov commented
@istraka thanks a lot for your input. 

I did some additional analysis and found out the tests are passing when they are not run with _CustomMetricCustomConfigSource*_ tests (hereinafter _Tests_). Obviously there is an issue with module configuration (adding/removing). 

But due the lack of time and my experience in MP Config I ended up with a different approach - moving _Tests_ to the separate Maven test step - in other words, all tests besides the _Tests_ are run in the first phase, while the _Tests_ are run in the second phase.

Passing job link is in the PR description.

2020-09-09 11:03 UTC, istraka commented
I see. This is definitely a better workaround than the one before. However this would bring another complexity to the TS and the issue would be still there. We should either fix the issue or be very sure this is the only option available. Feel free to reach me out on a gchat to discuss the technical details.

2020-09-11 08:15 UTC, zhantemirov commented
PR does not make sense anymore due to the latest commentaries in the reported JIRA - https://issues.redhat.com/browse/WFLY-13779

2020-09-11 08:15 UTC, closed without merging